---
title: "R_team3"
author: "hansu"
date: "2022-08-09"
output: html_document
---

## R 팀 프로젝트 3조 구성 및 역할

정한수-조장 bakery 자료를 이용하여 빵집 매출 내역 분석

김지윤 titanic 자료내의 여러 범주별 생존비율율 분석

신민수 HousePrices 자료 중 주거공간, 차고 관련 정보에 초점을 두고 분석

이재상 Pima Indians Diabetes Database자료에서 당뇨병의 원인이 되는 요인 탐색

방영찬 Spaceship Titanic 자료를 이용해 기존 titanic 과는 다른 접근으로 분석

  
  
  

## 전체 프로젝트 정리

R 프로그램을 통해서 여러자료를 다루는 방법을 연습
전체적으로 자료의 원래 목적에 맞게 특정 목표변수에 대한  
변수들의 상관성을 파악하기는 힘들었지만 여러방식으로 접근을 해보았다.
  
  
  



## 프로젝트 진행중 특이사항
#### 정한수
- 빵집의 매출 기록 자료에서 이상치를 찾고 메뉴별, 요일/월별 매출 기록을 시각화화 
  

#### 신민수
- 너무 많은 범주를 가지는 범주형 데이터의 자료형을 바꾸고 여러 범주를 요약해서 재설정하는 것이 어려웠음,  
유효한 열을 찾아 특정 column에 집중하여 분석을 진행
  
  
#### 김지윤
- 나이 자료 내의 결측치가 많아 처리방법을 고민,  여러 범주별로 그래프 그리기를 시도,  
나이 자료를 범주화하여 분석에 활용
  
  
#### 방영찬 
- Spaceship Titanic 자료에 서비스 이용 자료에서 0 으로 표시된 자료가 많아서 고민 하다  
이용 여부를 나타내는 범주를 새로 만들어 주어 분석을 실시  
여러 정보가 하나의 문자열로 축약된 열을 분석에 용이하도록 변경 후 분석
  
  
#### 이재상
- 당뇨관련 자료에서 0을 보이는 자료가 많았는데 그중 인슐린 수치가 0인 경우가 있고 해당 자료가  
실제로 인슐린 수치가 0임을 의미하는지 아니면 결측을 의미하는지 이해하는데 어려움을 겪음
